name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"
  
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v0.18.0
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          dark_mode: true

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: actions/upload-artifact@v2
        with:
          name: SVG Files
          path: dist/
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
